CREATE or REPLACE TRIGGER LOGOFF_LOG
    BEFORE LOGOFF ON DATABASE
BEGIN
    INSERT INTO LOG_ESTOQUE (USUARIO, DATA_LOG, ACAO)
    VALUES (USER, SYSDATE, 'Desconectou');
END LOGOFF_LOG;

-- Desativando uma trigger
-- ALTER TRIGGER Desconectou DISABLE