alter TABLE ESTOQUE ADD QUANTIDADE NUMBER(10) DEFAULT 3 NOT NULL;

CREATE TABLE VENDAS (
    VEN_CODIGO NUMBER(10) PRIMARY KEY,
    VEN_CODIGO_PRODUTO NUMBER(10),
    VEN_QUANTIDADE NUMBER(10)
    --CONSTRAINT FK_VENDAS_ESTOQUE FOREIGN KEY (VEN_CODIGO_PRODUTO) REFERENCES ESTOQUE (CODIGO)
);

--INSERT INTO VENDAS (VEN_CODIGO, VEN_CODIGO_PRODUTO, VEN_QUANTIDADE) VALUES (1, 101, 5);
--INSERT INTO VENDAS (VEN_CODIGO, VEN_CODIGO_PRODUTO, VEN_QUANTIDADE) VALUES (2, 102, 10);
--INSERT INTO VENDAS (VEN_CODIGO, VEN_CODIGO_PRODUTO, VEN_QUANTIDADE) VALUES (3, 103, 15);
--INSERT INTO VENDAS (VEN_CODIGO, VEN_CODIGO_PRODUTO, VEN_QUANTIDADE) VALUES (4, 104, 20);

SELECT * from ESTOQUE;
SELECT * from VENDAS;

INSERT INTO VENDAS (VEN_CODIGO, VEN_CODIGO_PRODUTO, VEN_QUANTIDADE) VALUES (1, 101, 1);
