create or REPLACE TRIGGER TRG_BAIXA_ESTOQUE
AFTER INSERT OR UPDATE OF VEN_QUANTIDADE on VENDAS
FOR EACH ROW
BEGIN
    UPDATE ESTOQUE SET QUANTIDADE = QUANTIDADE - :NEW.VEN_QUANTIDADE 
    WHERE EST_CODIGO = :NEW.VEN_CODIGO;
END;

--ALTER TRIGGER TRG_BAIXA_ESTOQUE ENABLE;
--ALTER TRIGGER update_job_history DISABLE [1]

-- SELECT * from ESTOQUE;
-- SELECT * from VENDAS;

--UPDATE ESTOQUE SET QUANTIDADE = 10 WHERE EST_CODIGO = 1;

-- INSERT INTO VENDAS (VEN_CODIGO, VEN_CODIGO_PRODUTO, VEN_QUANTIDADE) VALUES (1, 101, 5);

-- SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
-- FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
-- WHERE TABLE_NAME = 'VENDAS';