create or REPLACE TRIGGER "BAIXA_ESTOQUE"
AFTER INSERT OR UPDATE or DELETE VEN_QUANTIDADE on VENDAS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE ESTOQUE SET QUANTIDADE = QUANTIDADE - :NEW.VEN_QUANTIDADE 
        WHERE EST_CODIGO = :NEW.VEN_CODIGO;
    END IF;
    ELSIF DELETING THEN
        UPDATE ESTOQUE SET QUANTIDADE = QUANTIDADE + :OLD.VEN_QUANTIDADE 
        WHERE EST_CODIGO = :OLD.VEN_CODIGO;
    END IF;
END;

