
DROP TABLE Vendas;
DROP TABLE Estoque;

CREATE TABLE Estoque (
    EST_CODIGO NUMBER PRIMARY KEY,
    EST_DESCRICAO VARCHAR2(100),
    EST_QUANTIDADE NUMBER
);

CREATE TABLE Vendas (
    VEN_CODIGO NUMBER PRIMARY KEY,
    VEN_CODIGO_PRODUTO NUMBER,
    VEN_QUANTIDADE NUMBER,
    CONSTRAINT fk_estoque
        FOREIGN KEY (VEN_CODIGO_PRODUTO)
        REFERENCES Estoque(EST_CODIGO)
);

SELECT * FROM Estoque;
SELECT * FROM VENDAS;



INSERT INTO ESTOQUE VALUES(1, 'BANANA', 130);

INSERT INTO VENDAS VALUES(1, 1, 100);
UPDATE ESTOQUE SET EST_QUANTIDADE = 700 WHERE EST_CODIGO = 1;

UPDATE VENDAS SET VEN_QUANTIDADE = 37 WHERE VEN_CODIGO = 1;
